# Generated by Django 3.0.4 on 2020-03-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='id',
            new_name='imdb_id',
        ),
    ]
