# Generated by Django 3.0.4 on 2020-03-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0002_auto_20200329_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_film', to='films.Film')),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
