# Generated by Django 3.0.4 on 2020-03-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_suggest'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='box_office',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
