# Generated by Django 3.0.4 on 2020-04-01 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0005_delete_suggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_film', to='films.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=100)),
                ('action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Action')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to=settings.AUTH_USER_MODEL)),
                ('suggest', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Suggestion')),
            ],
        ),
    ]
