# Generated by Django 3.0.4 on 2020-03-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_watched_films'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watched_films',
            new_name='watch_films',
        ),
    ]
