# Generated by Django 3.0.4 on 2020-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_suggest'),
        ('accounts', '0006_auto_20200329_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suggests',
            field=models.ManyToManyField(blank=True, related_name='suggests', to='films.Suggest'),
        ),
    ]
