# Generated by Django 3.0.4 on 2020-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200331_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='suggests',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='avatars/'),
        ),
    ]
