# Generated by Django 3.0.4 on 2020-04-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200402_0834'),
        ('accounts', '0009_auto_20200401_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='api.Notification'),
        ),
    ]
